
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/domini/.opencode/bin/"
      - "/home/domini/.cargo/bin/"
      - "/home/domini/.local/bin/"
      - "/home/domini/.local/share/pnpm/"
      - "/opt/sonar-scanner/bin/"
      - "/home/domini/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/opt/android-sdk/platform-tools/"
      - "/opt/android-sdk/tools/"
      - "/opt/android-sdk/tools/bin/"
      - "/opt/cuda/bin/"
      - "/usr/share/dotnet/"
      - "/home/domini/.dotnet/tools/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/opt/llvm-mingw/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/opt/rocm/bin/"
      - "/home/domini/.bin/"
      - "/usr/bin/unstable/"
      - "/home/domini/bin/"
      - "/bin/"
    searched_directories:
      - "/home/domini/.opencode/bin/uname"
      - "/home/domini/.cargo/bin/uname"
      - "/home/domini/.local/bin/uname"
      - "/home/domini/.local/share/pnpm/uname"
      - "/opt/sonar-scanner/bin/uname"
      - "/home/domini/.nix-profile/bin/uname"
      - "/nix/var/nix/profiles/default/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/domini/.opencode/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/share/pnpm"
        - "/home/domini/.cargo/bin"
        - "/opt/sonar-scanner/bin"
        - "/home/domini/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/opt/android-sdk/platform-tools"
        - "/opt/android-sdk/tools"
        - "/opt/android-sdk/tools/bin"
        - "/opt/cuda/bin"
        - "/usr/share/dotnet"
        - "/home/domini/.dotnet/tools"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/opt/llvm-mingw/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/opt/rocm/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.18.2-arch2-1-x64v4 - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/home/domini/.opencode/bin/"
      - "/home/domini/.cargo/bin/"
      - "/home/domini/.local/bin/"
      - "/home/domini/.local/share/pnpm/"
      - "/opt/sonar-scanner/bin/"
      - "/home/domini/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/opt/android-sdk/platform-tools/"
      - "/opt/android-sdk/tools/"
      - "/opt/android-sdk/tools/bin/"
      - "/opt/cuda/bin/"
      - "/usr/share/dotnet/"
      - "/home/domini/.dotnet/tools/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/opt/llvm-mingw/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/opt/rocm/bin/"
      - "/home/domini/.bin/"
      - "/usr/bin/unstable/"
      - "/home/domini/bin/"
    searched_directories:
      - "/home/domini/.opencode/bin/gmake"
      - "/home/domini/.cargo/bin/gmake"
      - "/home/domini/.local/bin/gmake"
      - "/home/domini/.local/share/pnpm/gmake"
      - "/opt/sonar-scanner/bin/gmake"
      - "/home/domini/.nix-profile/bin/gmake"
      - "/nix/var/nix/profiles/default/bin/gmake"
      - "/usr/local/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/usr/bin/gmake"
      - "/opt/android-sdk/platform-tools/gmake"
      - "/opt/android-sdk/tools/gmake"
      - "/opt/android-sdk/tools/bin/gmake"
      - "/opt/cuda/bin/gmake"
      - "/usr/share/dotnet/gmake"
      - "/home/domini/.dotnet/tools/gmake"
      - "/var/lib/flatpak/exports/bin/gmake"
      - "/usr/lib/jvm/default/bin/gmake"
      - "/opt/llvm-mingw/bin/gmake"
      - "/usr/bin/site_perl/gmake"
      - "/usr/bin/vendor_perl/gmake"
      - "/usr/bin/core_perl/gmake"
      - "/opt/rocm/bin/gmake"
      - "/home/domini/.bin/gmake"
      - "/usr/bin/unstable/gmake"
      - "/home/domini/bin/gmake"
      - "/home/domini/.opencode/bin/make"
      - "/home/domini/.cargo/bin/make"
      - "/home/domini/.local/bin/make"
      - "/home/domini/.local/share/pnpm/make"
      - "/opt/sonar-scanner/bin/make"
      - "/home/domini/.nix-profile/bin/make"
      - "/nix/var/nix/profiles/default/bin/make"
      - "/usr/local/sbin/make"
      - "/usr/local/bin/make"
    found: "/usr/bin/make"
    search_context:
      ENV{PATH}:
        - "/home/domini/.opencode/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/share/pnpm"
        - "/home/domini/.cargo/bin"
        - "/opt/sonar-scanner/bin"
        - "/home/domini/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/opt/android-sdk/platform-tools"
        - "/opt/android-sdk/tools"
        - "/opt/android-sdk/tools/bin"
        - "/opt/cuda/bin"
        - "/usr/share/dotnet"
        - "/home/domini/.dotnet/tools"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/opt/llvm-mingw/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/opt/rocm/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:13 (find_program)"
    mode: "program"
    variable: "GHC_EXECUTABLE"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ghc"
    candidate_directories:
      - "/home/domini/.opencode/bin/"
      - "/home/domini/.cargo/bin/"
      - "/home/domini/.local/bin/"
      - "/home/domini/.local/share/pnpm/"
      - "/opt/sonar-scanner/bin/"
      - "/home/domini/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/opt/android-sdk/platform-tools/"
      - "/opt/android-sdk/tools/"
      - "/opt/android-sdk/tools/bin/"
      - "/opt/cuda/bin/"
      - "/usr/share/dotnet/"
      - "/home/domini/.dotnet/tools/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/opt/llvm-mingw/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/opt/rocm/bin/"
      - "/home/domini/.bin/"
      - "/usr/bin/unstable/"
      - "/home/domini/bin/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
    searched_directories:
      - "/home/domini/.opencode/bin/ghc"
      - "/home/domini/.cargo/bin/ghc"
      - "/home/domini/.local/bin/ghc"
      - "/home/domini/.local/share/pnpm/ghc"
      - "/opt/sonar-scanner/bin/ghc"
      - "/home/domini/.nix-profile/bin/ghc"
      - "/nix/var/nix/profiles/default/bin/ghc"
      - "/usr/local/sbin/ghc"
      - "/usr/local/bin/ghc"
    found: "/usr/bin/ghc"
    search_context:
      ENV{PATH}:
        - "/home/domini/.opencode/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/share/pnpm"
        - "/home/domini/.cargo/bin"
        - "/opt/sonar-scanner/bin"
        - "/home/domini/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/opt/android-sdk/platform-tools"
        - "/opt/android-sdk/tools"
        - "/opt/android-sdk/tools/bin"
        - "/opt/cuda/bin"
        - "/usr/share/dotnet"
        - "/home/domini/.dotnet/tools"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/opt/llvm-mingw/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/opt/rocm/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/usr/local"
        - "/usr"
        - "/"
        - "/usr"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:14 (find_program)"
    mode: "program"
    variable: "STACK_EXECUTABLE"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "stack"
    candidate_directories:
      - "/home/domini/.opencode/bin/"
      - "/home/domini/.cargo/bin/"
      - "/home/domini/.local/bin/"
      - "/home/domini/.local/share/pnpm/"
      - "/opt/sonar-scanner/bin/"
      - "/home/domini/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/opt/android-sdk/platform-tools/"
      - "/opt/android-sdk/tools/"
      - "/opt/android-sdk/tools/bin/"
      - "/opt/cuda/bin/"
      - "/usr/share/dotnet/"
      - "/home/domini/.dotnet/tools/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/opt/llvm-mingw/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/opt/rocm/bin/"
      - "/home/domini/.bin/"
      - "/usr/bin/unstable/"
      - "/home/domini/bin/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
    searched_directories:
      - "/home/domini/.opencode/bin/stack"
      - "/home/domini/.cargo/bin/stack"
      - "/home/domini/.local/bin/stack"
      - "/home/domini/.local/share/pnpm/stack"
      - "/opt/sonar-scanner/bin/stack"
      - "/home/domini/.nix-profile/bin/stack"
      - "/nix/var/nix/profiles/default/bin/stack"
      - "/usr/local/sbin/stack"
      - "/usr/local/bin/stack"
    found: "/usr/bin/stack"
    search_context:
      ENV{PATH}:
        - "/home/domini/.opencode/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.cargo/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.local/share/pnpm"
        - "/home/domini/.cargo/bin"
        - "/opt/sonar-scanner/bin"
        - "/home/domini/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/opt/android-sdk/platform-tools"
        - "/opt/android-sdk/tools"
        - "/opt/android-sdk/tools/bin"
        - "/opt/cuda/bin"
        - "/usr/share/dotnet"
        - "/home/domini/.dotnet/tools"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/opt/llvm-mingw/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/opt/rocm/bin"
        - "/home/domini/.local/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
        - "/home/domini/.bin"
        - "/usr/bin/unstable"
        - "/home/domini/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/usr/local"
        - "/usr"
        - "/"
        - "/usr"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
...
